# Summary of Legislative Changes in Local Taxation in 2019

## General Provisions

### Local License Tax on Mobile Food Units
Senate Bill 1425 (Chapter 791) provides that when the owner of a new business that operates a mobile food unit has paid a license tax as required by the locality in which the mobile food unit is registered, the owner is not required to pay a license tax to any other locality for conducting business from such mobile food unit in such a locality.[^0]

This  exemption  from  paying  the  license  tax  in  other  localities expires two years after the payment of the initial license tax in the locality in which the mobile food unit is registered. During the two year exemption period, the owner is  entitled  to  exempt  up  to  three  mobile  food  units  from  license taxation in other localities. However, the owner of the mobile food unit is required to register with the Commissioner  of  the  Revenue  or  Director  of  Finance  in  any  locality  in  which  he  conducts  business  from  such  mobile  food unit, regardless of whether the owner is exempt from paying license tax in the locality.
     
This Act defines “mobile food unit” as a restaurant that is mounted on wheels and readily moveable from place to place  at  all  times  during  operation.  It  also  defines  “new business” as a business that locates for the first time to do business in a locality. A business will not be deemed a new business  based  on  a  merger,  acquisition,  similar  business  combination, name change, or a change to its business form.
      
Without  the  exemption  provided  in  this  Act,  localities  are  authorized  to  impose  business,  professional  and  occupational license (BPOL) taxes upon local businesses. Generally,  the  BPOL  tax  is  levied  on  the  privilege  of  engaging in business at a definite place of business within a  Virginia  locality.  Businesses  that  are  mobile,  however,  can be subject to license taxes or fees in multiple localities in certain situations.
      
Effective: July 1, 2019

Added: § 58.1-3715.1


### Local Gas Road Improvement Tax; Extension of Sunset Provision
House Bill 2555 (Chapter 24) and Senate Bill 1165 (Chapter 191) extend the sunset date for the local gas road improve-ment  tax  from  January  1,  2020  to  January  1,  2022.  The authority to impose the local gas road improvement tax was previously scheduled to sunset on January 1, 2020.

The  localities  that  comprise  the  Virginia  Coalfield Economic Development Authority may impose a local gas road improvement tax that is capped at a rate of one percent of the gross receipts from the sale of gases severed within the  locality.  Under  current  law,  the  revenues  generated  from this tax are allocated as follows: 75% are paid into a special fund in each locality called the Coal and Gas Road Improvement Fund, where at least 50% are spent on road improvements  and  25%  may  be  spent  on  new  water  and  sewer systems or the construction, repair, or enhancement of natural gas systems and lines within the locality; and the remaining 25% of the revenue is paid to the Virginia Coal-fi eld Economic Development Fund. The Virginia Coalfi eld Economic Development Authority is comprised of the City of Norton, and the Counties of Buchanan, Dickenson, Lee, Russell, Scott, Tazewell, and Wise.

Effective: July 1, 2019

Amended: § 58.1-3713

### Private Collectors Authorized for Use by Localities to Collect Delinquent Debts
Senate Bill 1301 (Chapter 271) allows a local treasurer to employ private collection agents to assist with the collection of delinquent amounts due other than delinquent local taxes that have been delinquent for a period of three months or more  and  for  which  the  appropriate  statute  of  limitations  has not run.

Effective: July 1, 2019

Amended: § 58.1-3919.1

## Real Property Tax

### Real Property Tax Exemptions for Elderly and Disabled: Computation of Income Limitation
House Bill 1937 (Chapter 16) provides that, if a locality has established a real estate tax exemption for the elderly and handicapped  and  enacted  an  income  limitation  related  to  the exemption, it may exclude, for purposes of calculating the income limitation, any disability income received by a family member or nonrelative who lives in the dwelling and who is permanently and totally disabled.

Under  current  law,  if  a  locality’s  tax  relief  ordinance  establishes an annual income limitation, the computation of annual income is calculated by adding together the income received during the preceding calendar year of the owners of the dwelling who use it as their principal residence; and the owners’ relatives who live in the dwelling, except for those  relatives  living  in  the  dwelling  and  providing bona  fide caregiving services to the owner whether such relatives are compensated or not; and at the option of each locality, nonrelatives of the owner who live in the dwelling except for bona fide tenants or bona fide caregivers of the owner, whether compensated or not.

Effective: July 1, 2019

Amended: § 58.1-3212

### Real Property Tax Exemption for Elderly and Disabled: Improvements to a Dwelling
House Bill 2150 (Chapter 736) and Senate Bill 1196 (Chapter 737) clarify the definition of “dwelling,” for purposes of the real property tax exemption for owners who are 65 years of age or older or permanently and totally disabled, to include certain improvements to the exempt land and the land on which  the  improvements  are  situated.  These  Acts  define the term “dwelling” to include an improvement to the land that is not used for a business purpose but is used to house certain motor vehicles or household goods.

Under current law, in order to be granted real property tax relief, qualifying property must be owned by and occupied as the sole dwelling of a person who is at least 65 years of age, or, if the local ordinance provides, any person with a permanent disability. Dwellings jointly held by spouses, with no other joint owners, qualify if either spouse is 65 or over or permanently and totally disabled.

Effective: July 1, 2019

Amended: § 58.1-3210

### Real Property Tax: Partial Exemption from Real Property Taxes for Flood Mitigation Efforts
Senate Bill 1588 (Chapter 754) enables a locality to provide by ordinance a partial exemption from real property taxes for flooding abatement, mitigation, or resiliency efforts for improved real estate that is subject to recurrent flooding, as authorized by an amendment to Article X, Section 6 of the Constitution of Virginia that was adopted by the voters on November 6, 2018.

This act provides that exemptions may only be granted for qualifying flood improvements that do not increase the size  of  any  impervious  area  and  are  made  to  qualifying  structures  or  to  land.  “Qualifying  structures”  are  defined as structures that were completed prior to July 1, 2018 or were completed more than 10 years prior to the completion of the improvements. For improvements made to land, the improvements  must  be  made  primarily  for  the  benefit  of one  or  more  qualifying  structures.  No  exemption  will  be  authorized for any improvements made prior to July 1, 2018.

A locality is granted the authority to (i) establish flood protection  standards  that  qualifying  flood  improvements must  meet  in  order  to  be  eligible  for  the  exemption;  (ii)  determine the amount of the exemption; (iii) set income or property  value  limitations  on  eligibility;  (iv)  provide  that  the exemption shall only last for a certain number of years; (v) determine, based upon flood risk, areas of the locality where  the  exemption  may  be  claimed;  and  (vi)  establish  preferred actions for qualifying for the exemption, including living shorelines.

Effective: July 1, 2019

Amended: § 58.1-3228.1

### Real Property Tax: Exemption for Certain Surviving Spouses
House Bill 1655 (Chapter 15) and Senate Bill 1270 (Chapter 801) allow surviving spouses of disabled veterans to continue  to  qualify  for  a  real  property  tax  exemption  regardless of whether the surviving spouse moves to a different residence, as authorized by an amendment to subdivision (a) of Section 6-A of Article X of the Constitution of Virginia that was adopted by the voters on November 6, 2018. If a surviving  spouse  was  eligible  for  the  exemption  but  lost  such eligibility due to a change in residence, then the surviving spouse is eligible for the exemption again, beginning January 1, 2019.

These Acts also clarify that the real property tax exemptions for spouses of service members killed in action and spouses  of  certain  emergency  service  providers  killed  in  the line of duty continue to apply regardless of the spouse’s moving to a new principal residence. 

Effective: Taxable years beginning on or after January 1, 2019

Amended: §§ 58.1-3219.5, 3219.9, and 3219.14

### Land Preservation; Special Assessment, Optional Limit on Annual Increase in Assessed Value
House  Bill  2365  (Chapter  22)  authorizes  localities  that  employ  use  value  assessments  for  certain  classes  of  real  property to provide by ordinance that the annual increase in the assessed value of eligible property may not exceed a specified dollar amount per acre. 

Effective: July 1, 2019

Amended: § 58.1-3231

### Virginia Regional Industrial Act: Revenue Sharing; Composite Index
House Bill 1838 (Chapter 534) requires that the Department of  Taxation’s  calculation  of  the  true  values  of  real  estate  and  public  service  company  property  component  of  the  Commonwealth’s  educational  composite  index  of  local  ability-to-pay take into account arrangements by localities entered  into  pursuant  to  the  Virginia  Regional  Industrial  Facilities Act, whereby a portion of tax revenue is initially paid to one locality and redistributed to another locality. This Act requires such calculation to properly apportion the percentage of tax revenue ultimately received by each locality.

Effective: July 1, 2021

Amended: § 58.1-6407

### Real Estate with Delinquent Taxes or Liens: Appointment of Special Commissioner; Increase Required Value
House Bill 2060 (Chapter 541) increases the assessed value of a parcel of land that could be subject to appointment of a special commissioner to convey the real estate to a locality as a result of unpaid real property taxes or liens from \$50,000or less to \$75,000 or less in most localities. In the Cities of Norfolk, Richmond, Hopewell, Newport News, Petersburg, Fredericksburg, and Hampton, this Act increases the threshold from \$100,000 or less to \$150,000 or less.

Effective: July 1, 2019

Amended: § 58.1-3970.1

### Real Estate with Delinquent Taxes or Liens; Appointment of Special Commissioner in the City of Martinsville
House Bill 2405 (Chapter 159) adds the city of Martinsville to the list of cities (Norfolk, Richmond, Hopewell, Newport News, Petersburg, Fredericksburg, and Hampton) that are authorized  to  have  a  special  commissioner  convey  tax-delinquent  real  estate  to  the  locality  in  lieu  of  a  public  sale  at  auction  when  the  tax-delinquent  property  has  an  assessed value of \$100,000 or less. House Bill 2060 raises the threshold in all of these cities from \$100,000 or less to \$150,000 or less.

Effective: July 1, 2019

Amended: § 58.1-3970.1

## Personal Property Tax

### Constitutional Amendment: Personal Property Tax Exemption for Motor Vehicle of a Disabled Veteran
House Joint Resolution 676 (Chapter 822) is a fi rst resolu-tion  proposing  a  constitutional  amendment  that  permits  the  General  Assembly  to  authorize  the  governing  body  of  any  county,  city,  or  town  to  exempt  from  taxation  one  motor vehicle of a veteran who has a 100 percent service-connected, permanent, and total disability. The amendment provides  that  only  automobiles  and  pickup  trucks  qualify  for the exemption.

Additionally,  the  exemption  will  only  be  applicable  on  the  date  the  motor  vehicle  is  acquired  or  the  effective date of the amendment, whichever is later, but will not be applicable for any period of time prior to the effective date of the amendment.

Effective: July 1, 2019

### Personal Property Tax Exemption for Agricultural Vehicles
House  Bill  2733  (Chapter  259)  expands  the  definition of agricultural use motor vehicles for personal property taxation purposes. It changes the criteria from motor vehicles used “exclusively”  for  agricultural  purposes  to  motor  vehicles  used  “primarily”  for  agricultural  purposes,  and  for  which  the owner is not required to obtain a registration certificate, license plate, and decal or pay a registration fee.

It also expands the definition of trucks or tractor trucks that are used by farmers in their farming operations for the transportation  of  farm  animals  or  other  farm  products  or  for the transport of farm-related machinery. The criteria is changed from vehicles used “exclusively” by farmers in their farming operations to vehicles used “primarily” by farmers in their farming operations.

Further,  this  Act  expands  the  classifi  cation  of  farm  machinery and equipment that a local governing body may exempt,  to  include  equipment  and  machinery  used  by  a  nursery  for  the  production  of  horticultural  products,  and  any farm tractor, regardless of whether such farm tractor is used exclusively for agricultural purposes.

Local  governing  bodies  have  the  option  to  exempt  these classifi cations, in whole or in part, from taxation or to provide for a different rate of taxation thereon.

Effective: July 1, 2019

Amended: § 58.1-3505

### Intangible Personal Property Tax: Classifi cation of Certain Business Property
House Bill 2440 (Chapter 255) classifies as intangible per-sonal  property,  tangible  personal  property:  i)  that  is  used  in a trade or business; ii) with an original cost of less than $25; and iii) that is not classified as machinery and tools, merchants’  capital,  or  short-term  rental  property.  It  also  exempts such property from taxation.

Intangible personal property is a separate class of prop-erty  segregated  for  taxation  by  the  Commonwealth.  The  Commonwealth does not currently tax intangible personal property.  Localities  are  prohibited  from  taxing  intangible  personal property.

Certain  personal  property,  while  tangible  in  fact,  has  previously been designated as intangible and thus exempted from state and local taxation. For example, tangible personal property  used  in  manufacturing,  mining,  water  well  drill-ing, radio or television broadcasting, dairy, dry cleaning, or laundry businesses has been designated as exempt intangible personal property.

Effective: July 1, 2019

Amended: §§ 58.1-1101 and 58.1-1103


----------------------------------------------------------------------------------------------------------

[^0]:  Excerpted from the local tax legislation section of the Department of Taxation’s 2019 Legislative Summary. Minor changes were made in format and punctuation. See https://tax.virginia.gov/legislative-sum-mary-reports