# Service Charges on Tax-Exempt Property

Sections 58.1-3400 through 58.1-3407 of the *Code of Virginia* authorize localities to impose service charges on otherwise tax-exempt property. Several types of property are excluded from this provision, including the land and buildings of churches used exclusively for worship and property used exclusively for nonprofit private educational or charitable purposes.

In 1981, the Virginia General Assembly amended the *Code* to restrict the use of the service charge on the value of real estate owned by the commonwealth to those localities where such property—excluding hospitals, educational institutions, roadway property, or property held for future construction—exceeds 3 percent of the value of all real estate located within the jurisdiction’s boundaries. However, the service charge may still be levied on faculty and staff housing owned by state educational institutions and on property of the Virginia Port Authority, regardless of the portion of state-owned property located within the locality.

The service charge is based on the assessed value of the state- or privately-owned real estate and the amount the locality has expended in furnishing police and fire protection, refuse collection and disposal, and the cost of public school education (applicable only in the case of faculty and staff housing of an educational institution). These expenditures must exclude any federal or state grants specifically designated for these purposes and any assistance provided to localities under Title 14.1, Article 10, Law-Enforcement Expenditures, of the *Code of Virginia*. If such services are not provided to the tax-exempt real estate or are funded by another service charge, the expenditures may not be included in calculations.

For (1) properties owned by religious organizations and used for religious purposes or (2) properties used for private, nonprofit educational or charitable purposes, the service charge may not exceed 20 percent of the real estate tax rate (or 50 percent in the case of faculty and staff housing at private educational institutions). The charge is determined by dividing the expenditures, as defined in the previous paragraph, by the assessed fair market value of all the real estate within the locality, except real estate owned by the United States government or by any of its instrumentalities. 

The city of Richmond, as the seat of state government, clearly satisfies the 3 percent requirement. In addition, a number of other localities impose service charges either because they have faculty and staff housing or because they claim to exceed the 3 percent rule. The primary reason for the claim is the presence of a state institution of higher education or of a state correctional institution. However, in instances where the 3 percent requirement may not have been reached, an affected state agency may voluntarily have agreed to pay a service charge.

Based on the survey and some follow-up conversations, it was found that localities that have state educational institutions and which also charge the service fee include the cities of Charlottesville (University of Virginia), Fredericksburg (University of Mary Washington), Harrisonburg (James Madison University), Lexington (Virginia Military Institute), and Wise County (University of Virginia at Wise). Counties that impose service charges based on the presence of correctional institutions include Brunswick (Brunswick Correctional Center and Brunswick Work Center for Women), Buckingham (Buckingham Correctional Center and Dillwyn Correctional Center), Greensville (Greensville Correctional Center and Greensville Work Center), Fluvanna (Fluvanna Correctional Center for Women), Southampton (Southampton Correctional Center, Southampton Work Center for Men, Southampton Pre-Release and Work Center for Women, and Deerfield Correctional Center), and Wise (Red Onion State Prison, Wallens Ridge State Prison, and Wise Correctional Unit #18). **Table 7.1** shows that 12 cities, 7 counties, and 1 town report imposing a service charge of some sort on state-owned or privately-owned property.

```{r}
# Table 7.1 Service Charges on Tax-exempt Property, 2019
```
