# Impact Fees for Roads

The  Code  of  Virginia  §  15.2-2319  authorizes  localities  identified  by  population  or  adjacency  to  certain  localities  (see § 15.2-2317) to assess and impose impact fees on new developments to pay all or part of the cost of reasonable road improvements attributable in substantial part to such development.  Costs  include,  in  addition  to  all  labor,  materials,  machinery, and equipment for construction, (i) acquisition of land, rights-of-way, property rights, easements, and interests, including the costs of moving or relocating utilities; (ii) demolition or removal of any structure on land so acquired, including acquisition of land to which such structure may be moved; (iii) survey, engineering, and architectural expenses; (iv) legal, administrative, and other related expenses; and (v) interest charges and other financing costs if impact fees are used for the payment of principal and interest on bonds, notes, or other obligations issued by the county, city, or town to finance the road improvements (§ 15.2-2318).

Before it can adopt an enabling ordinance, the locality must establish an impact fee advisory committee (§ 15.2-2319).  The  locality  may  then  delineate  one  or  more  impact fee service areas. Any impact fees collected from new development within an impact fee service area must be expended for road improvements in that impact fee service area (§ 15.2-2320).

Prior to adopting a system of impact fees, localities must conduct an assessment of road improvement needs benefitting an impact fee service area. From this needs assessment, a  road  improvement  plan  must  be  developed  to  improve  existing roads and construct new roads within the impact fee service area. The improvement plan will then be incorporated into the locality’s capital improvements program after a duly advertised public hearing (§ 15.2-2321).

After  the  adoption  of  the  improvement  program,  the  locality  may  adopt  an  ordinance  establishing  a  system  of  impact fees to fund or recapture the cost of providing road improvements  within  the  impact  fee  service  areas.  The  ordinance  will  list  a  schedule  of  the  impact  fees  for  each  service area (§ 15.2-2322).

Section  15.2-2323  specifies  that  the  impact  fee  for  a  specific  development  or  subdivision  must be  determined  prior to or at the time when the site is approved. The ordinance must specify that the payment of fees be in one lump sum or through installments at a reasonable rate of interest for a fixed number of years. 

The 2007 transportation funding legislation [House Bill 3202 (Chapter 896)] authorized localities with established urban transportation service districts to impose additional impact  fees  subject  to  certain  restrictions  (§  15.2-2320).  Service  districts  are  districts  created  within  a  locality  “to  provide additional, more complete or more timely services of government than are desired in the locality or localities as a whole” (§ 15.2-2400). The urban transportation service district had to be established in accordance with § 15.2-2403.1 in those counties which met the definition of urban county –  “any  county  with  a  population  of  greater  than  90,000,  according to the United States Census of 2000, that did not maintain its roads as of January 1, 2007” (§ 15.2-2403.1). The counties have to maintain the roads within the district.

The 2007 law applied only to counties with urban transportation service districts and had to be exercised in areas of the county outside of already established urban transportation service districts in parcels zoned agricultural that were being subdivided  for  by-right  residential  development.  Also,  the  authority for the article expired on December 31, 2008 for any locality that had not established an urban transportation service district and adopted an impact fee ordinance in the new area by that date.

The  law  permits  urban  counties  with  existing  urban  transportation  service  districts  to  create  new  impact  fee  service  areas.  The  locality  must  include  within  its  capital  improvements  plan  estimates  of  costs  for  public  facilities  necessary  to  serve  residential  uses.  Such  public  facilities  include but are not limited to: (i) roads, bridges, and signals; (ii) storm water and flood control facilities; (iii) parks, open space,  and  recreation  areas;  (iv)  public  safety  facilities;  (v) primary and secondary schools; (vi) libraries and related facilities (§ 15.2-2320). Only Stafford County reports having used this authority to impose new fees. **Table 22.1** lists four counties and one city that reported using impact fees. 

```{r}
#Table 22.1 "Impact Fees For Road Improvement, 2019" goes here
```
