# Public Rights-of-Way Use Fees

The Code of Virginia § 56-468.1 authorizes certain localities to charge rights-of-way use fees for the use of publicly owned roads  and  property  by  certified  telecommunication firms. Cities and towns whose public streets are not maintained by the Virginia Department of Transportation (VDOT), as well as any county that has chosen to withdraw from the secondary system of state highways (currently only Arlington and Henrico counties), may impose a public rights-of-way use fee by local ordinance. This fee is in exchange for the use of the locality’s lands for electric poles or electric conduits by certified providers of telecommunications services. 

The provider collects the use fee on a per access line basis by adding the fee to each end-user’s monthly bill for local exchange telephone service (§ 56-468-1.G). The fee must be stated separately on the phone bill.

The fee is calculated each year by VDOT based on information  about  the  number  of  access  lines  and  footage  of  new  installation that have occurred in the reporting localities. Based on  this  information,  VDOT  uses  a  formula  to  calculate  the  monthly fee per access line for participating localities. Starting July  1,  2019,  the  fee  was  $1.20  per  access  line.  Information  about the rights-of-way use fee can be obtained from VDOT at: http://www.virginiadot.org/business/row-usefee.asp. The Code(§ 56-468.1.I) also permits any locality which had a franchise agreement or ordinance prior to July 1, 1998 to “grandfather” in the prior agreement provided that the county, city, or town does not discriminate among telecommunications providers and does not adopt any additional rights-of-way practices that do not comply with current laws.

***Table 23.1*** lists the localities that report having a rights-of-way agreement or a prior agreement that has been grand-fathered. The information is based on the Cooper Center’s 2019 survey. The text table below summarizes the results:   

```{r}
#Text table "Public Rights-of-Way Use Fees, 2019" goes here

#Table 23.1 "Localities Imposing Public Rights-of-Way Use Fees, 2019*" goes here
```



* In years prior to 2009 this table was based on information provided by the Virginia Department of Transportation. The current table uses data based on responses to the Cooper Center’s survey. To compare survey responses with VDOT information, refer to http://virginiadot.org/business/row-usefee.asp
